import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
  console.log("Custom key from env: ", process.env.customKey);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}

        <h1>Welcome Anarya</h1>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <p className={styles.description}>
          Explore your interest today!
        </p>

        <div className={styles.grid}>
          {/* <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a> */}

          <Link href="/about">
            <a className={styles.card}>
              <h2>About</h2>
            </a>
          </Link>

          <Link href="/news">
            <a className={styles.card}>
              <h2>News</h2>
            </a>
          </Link>

          <Link href="/apiList">
            <a className={styles.card}>
              <h2>API</h2>
            </a>
          </Link>

          <Link href="/csr">
            <a className={styles.card}>
              <h2>Client Side Rendering (CSR)</h2>
            </a>
          </Link>

          <Link href="/ssr">
            <a className={styles.card}>
              <h2>Server Side Rendering (SSR)</h2>
            </a>
          </Link>

          <Link href="/ssg">
            <a className={styles.card}>
              <h2>Static Side Generation (SSG)</h2>
            </a>
          </Link>

          <Link href="/isr">
            <a className={styles.card}>
              <h2>Incremental Static Regeneration (ISR)</h2>
            </a>
          </Link>

          {/* <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
