/**
 * @stylingDependencies
 */
// Local Styling Dependencies
import styles from '../styles/Home.module.css';

/**
 * @componentDependencies
 */
// NextJS Components Dependencies
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
  console.log("Custom key from env: ", process.env.customKey);

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <header>
          <h1 className={styles.title}>Welcome Anarya</h1>
          <p className={styles.description}>Explore your interest today!</p>
        </header>

        <div className={styles.grid}>
          <Link href="/about">
            <a className={styles.card}>
              <h2>About</h2>
            </a>
          </Link>

          <Link href="/news">
            <a className={styles.card}>
              <h2>News</h2>
            </a>
          </Link>

          <Link href="/apiList">
            <a className={styles.card}>
              <h2>API</h2>
            </a>
          </Link>

          <Link href="/csr">
            <a className={styles.card}>
              <h2>Client Side Rendering (CSR)</h2>
            </a>
          </Link>

          <Link href="/ssr">
            <a className={styles.card}>
              <h2>Server Side Rendering (SSR)</h2>
            </a>
          </Link>

          <Link href="/ssg">
            <a className={styles.card}>
              <h2>Static Side Generation (SSG)</h2>
            </a>
          </Link>

          <Link href="/isr">
            <a className={styles.card}>
              <h2>Incremental Static Regeneration (ISR)</h2>
            </a>
          </Link>

          <Link href="/categories">
            <a className={styles.card}>
              <h2>Categories</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
